/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const AmbientLight: typeof import('three')['AmbientLight']
  const BoxGeometry: typeof import('three')['BoxGeometry']
  const Clock: typeof import('three')['Clock']
  const DepthFormat: typeof import('three')['DepthFormat']
  const DepthTexture: typeof import('three')['DepthTexture']
  const GUI: typeof import('three/examples/jsm/libs/lil-gui.module.min')['GUI']
  const HemisphereLight: typeof import('three')['HemisphereLight']
  const IcosahedronGeometry: typeof import('three')['IcosahedronGeometry']
  const LineBasicMaterial: typeof import('three')['LineBasicMaterial']
  const Mesh: typeof import('three')['Mesh']
  const MeshBasicMaterial: typeof import('three')['MeshBasicMaterial']
  const NearestFilter: typeof import('three')['NearestFilter']
  const OrbitControls: typeof import('three/addons')['OrbitControls']
  const OrthographicCamera: typeof import('three')['OrthographicCamera']
  const PerspectiveCamera: typeof import('three')['PerspectiveCamera']
  const PlaneGeometry: typeof import('three')['PlaneGeometry']
  const Scene: typeof import('three')['Scene']
  const ShaderMaterial: typeof import('three')['ShaderMaterial']
  const Stats: typeof import('three/addons/libs/stats.module')['default']
  const TWEEN: typeof import('three/examples/jsm/libs/tween.module')['default']
  const UnsignedIntType: typeof import('three')['UnsignedIntType']
  const Vector3: typeof import('three')['Vector3']
  const WebGLRenderTarget: typeof import('three')['WebGLRenderTarget']
  const WebGLRenderer: typeof import('three')['WebGLRenderer']
}
